kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nodejs-sample-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node() {
          stage 'Build'
          openshiftBuild(buildConfig: 'myapp', showBuildLogs: 'true')
          
          stage 'Deploy'
          openshiftDeploy(deploymentConfig: 'myapp')
        }
    type: JenkinsPipeline
