apiVersion: v1
kind: BuildConfig
metadata:
  name: my-pipeline
labels:
    name: my-pipeline
annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    - type: GitHub
      github:
        secret: github
    - type: Generic
      generic:
        secret: generic
  runPolicy: Serial
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: >
        node("nodejs"){
            stage('Build App Image') {
              openshiftBuild(namespace: 'cicd-dev', buildConfig: 'myapp', showBuildLogs: 'true')
            }

            stage('Deploy Dev') {
              openshiftDeploy(namespace: 'cicd-dev', deploymentConfig: 'myapp')
            }

            stage('Deploy Stage') {
              input 'Souhaitez-vous déployer l\'application dans l\'environnement stage ?'
              openshiftTag(namespace: 'cicd-dev', sourceStream: 'myapp',sourceTag: 'latest', destinationStream: 'myapp', destinationTag:'stageReady')
              openshiftDeploy(namespace: 'cicd-stage', deploymentConfig: 'myapp')
            }
        }
    type: JenkinsPipeline
output: {}
resources: {}
postCommit: {}
